### ISSUE TITLE
About Readme

### ISSUE THREAD

**Issue by zcqzcg** [hyperledger-labs/fabex#88]
Any chance that we could provide a better readme or some sort of tutorials that build from ground?

**Comment by vadimInshakov** [comment]
@zcqzcg I will try to write a step by step guide and post it as soon as possible.

**Comment by vadimInshakov** [comment]
@zcqzcg https://vadiminshakov.medium.com/fabex-tutorial-an-introduction-to-the-right-hyperledger-fabric-explorer-cd9ee1848cd9

**Comment by zcqzcg** [comment]
Thanks! It's perfect!
